### ISSUE TITLE
Unary callback never executed

### ISSUE THREAD

**Issue by pinda** [grpc/grpc-swift#92]
Trying to build a simple app with this but in discovery I ran into the issue that the callback is not executed. In the example it shows:
`_ = try service.get(requestMessage) {responseMessage, callResult in ...`

If I try it with this piece of code it never goes to the completionHandler, also no error is thrown.

```
let service = Service(address: "127.0.0.1:50051")
let userRequest = RegisterRequest.with {
   $0.name = "foo"
 }

do {
    _ = try service.register(userRequest) {responseMessage, callResult in
      if let responseMessage = responseMessage {
           print(responseMessage.success)
       } else  {
           print("No message received. \(callResult)")
         }
      }
} catch {
    print(error)
}
```

when changing it to the following it does get executed:

```
let service = Service(address: "127.0.0.1:50051")
let userRequest = RegisterRequest.with {
   $0.name = "foo"
 }

do {
    let call = try service.register(userRequest) {responseMessage, callResult in
      if let responseMessage = responseMessage {
           print(responseMessage.success)
       } else  {
           print("No message received. \(callResult)")
         }
      }
    print(call) // Can imagine it will be evaluated at that point, but the example works otherwise.
} catch {
    print(error)
}
```

**Comment by pinda** [comment]
Another test I ran if I change it to the following, the sync will get executed every time but the callback not every time but most of the time.

```
let service = Service(address: "127.0.0.1:50051")
let userRequest = RegisterRequest.with {
   $0.name = "foo"
 }

do {
    let resp = try service.register(userRequest)
    print("sync: \(resp.success)")

    _ = try service.register(userRequest) {responseMessage, callResult in
      if let responseMessage = responseMessage {
           print(responseMessage.success)
       } else  {
           print("No message received. \(callResult)")
         }
      }
} catch {
    print(error)
}
```

**Comment by bilalyaylak** [comment]
@pinda Does second one work without printing 'call', but with assignment? 
I also couldn't achieve running async calls with completion closures. 

```swift
let service = Service(address: "127.0.0.1:50051")
let userRequest = RegisterRequest.with {
   $0.name = "foo"
 }

do {
    let call = try service.register(userRequest) {responseMessage, callResult in
      if let responseMessage = responseMessage {
           print(responseMessage.success)
       } else  {
           print("No message received. \(callResult)")
         }
      }
    print(call) // Can imagine it will be evaluated at that point, but the example works otherwise.
} catch {
    print(error)
}
```

**Comment by pinda** [comment]
@bilalyaylak no without printing it does not work for me

**Comment by KosukeOhmura** [comment]
@pinda same here..

**Comment by timburks** [comment]
If your code is in a stand-alone executable like a command-line tool (i.e. not a Mac or iOS app, which have run loops), then something has to block your program from exiting before the callback gets run. One way to do that is with DispatchSemaphores. For an example, see this modification that I've made to your original sample:

```
let service = Service(address: "127.0.0.1:50051")
let userRequest = RegisterRequest.with {
   $0.name = "foo"
 }

do {
  let sem = DispatchSemaphore(value: 0)
   _ = try service.register(userRequest) {responseMessage, callResult in
    if let responseMessage = responseMessage {
      print(responseMessage.success)
    } else  {
      print("No message received. \(callResult)")
    }
    sem.signal()
  }
} catch {
  print(error)
}
 _ = sem.wait(timeout: DispatchTime.distantFuture)
```

I guess your print statement slowed things down just enough to give the callback enough time to complete. 

You can look inside the [generated code for a synchronous unary call](https://github.com/grpc/grpc-swift/blob/0.3.2/Examples/Echo/Generated/echo.client.pb.swift#L48) and see that this is how the synchronous calls in the generated code are built on underlying asynchronous calls.

**Comment by pinda** [comment]
@timburks the examples posted are used in a Mac app. That's why I'd rather use the async version instead of the sync one. The synchronous version works without any issues.

**Comment by timburks** [comment]
@pinda If you are still having problems with this and can send me a small test case that reproduces your problem, I'll look at it.

**Comment by MrMage** [comment]
Could you please check if this got fully fixed with #184? Callbacks should now even be called when an operation fails.

**Comment by pinda** [comment]
Running into a couple of issues when installing through Cocoapods.
1. Include of non-modular header inside framework module 'grpc': '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/inttypes.h'
2. Could not build module 'grpc'

When adding manually I ran into a missing framework `gRPC`

**Comment by MrMage** [comment]
This is a known issue and can only be fixed once we can migrate to gRPC-Core 1.11, which has not been released yet. Also, that migration in turn would require to use the Swift 4.1 compiler. But you can see https://github.com/grpc/grpc-swift/issues/111#issuecomment-371311886 for a workaround, essentially you just need to pin the `gRPC-Core` package:

    pod 'gRPC-Core', :git => 'https://github.com/mrmage/grpc', :branch => 'fix-cocoapods-swift'

Also, make sure to use the current Swift source at head, not the one in version 0.3.3.

**Comment by pinda** [comment]
Thanks! Got one error I can't get rid of:
1. No such module 'gRPC'

its in my generated swift file from the proto. Am I still missing an import?

**Comment by MrMage** [comment]
Did you run the latest gRPC protobuf compiler? It has changed that to SwiftGRPC.

**Comment by pinda** [comment]
sorry, mixup with my binaries. But I am able to confirm that the callback works!
